version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalamos requirements"
      - pip install -r CloudwatchDefault/requirements.txt -t CloudwatchDefault/lib
      - pip install -r PutMetricsFunction/requirements.txt -t PutMetricsFunction/lib
  build:
    commands:
      - echo "Zipping deployment package function CloudwatchDefault..."
      - cd CloudwatchDefault/lib
      - zip -r9 ../CloudwatchDefault.zip .
      - cd ..
      - zip -g CloudwatchDefault.zip app.py
      - cd ..
      - echo "Zipping deployment package function PutMetricsFunction..."
      - cd PutMetricsFunction/lib
      - zip -r9 ../PutMetricsFunction.zip .
      - cd ..
      - zip -g PutMetricsFunction.zip app.py
      - cd ..
  post_build:
    commands:
      - echo "Uploading zip CloudwatchDefault to S3..."
      - aws s3 cp CloudwatchDefault/CloudwatchDefault.zip s3://pruebacodebuildjonatan
      - echo "Uploading zip PutMetricsFunction to S3..."
      - aws s3 cp PutMetricsFunction/PutMetricsFunction.zip s3://pruebacodebuildjonatan
      - echo "DONE!!"  
